### ISSUE TITLE
鸟哥 这个什么时候能出来？比Bd_Conf性能高，很期待~

### ISSUE THREAD

**Issue by yeshiquan** [laruence/yaconf#1]

**Comment by xdstack** [comment]
看到 Require PHP 7 + ，跪了。。 哈哈

**Comment by laruence** [comment]
现在你已经能用了啊....只不过只能在PHP7上用...

**Comment by wuleying** [comment]
PHP7... Orz..

**Comment by dwroy** [comment]
ini文件写多层的数组数据没有yml来得方便，要是能写一个解析yml的就好了

**Comment by kkshow** [comment]
也就是10月份才能用上了。。。鸟哥你这个明显是在偷懒啊

**Comment by laruence** [comment]
@kkshow  你说我把代码都搞出来了, 谁要做个PHP5的迁移, 也不是很简单的事情? -_#

**Comment by anyforever** [comment]
修改完配置，重启的时候有检测配置文件正确性的过程么？至少检查一个有没有语法错误的。还是依赖PHP遇到不符合语法的地方报错的？

**Comment by laruence** [comment]
你可以自己写一个脚本, 运行 "parse_ini_file" 如果成功就没问题

**Comment by laruence** [comment]
另外你可以通过phpinfo() 获取到cache了那些文件之类的信息...

**Comment by anyforever** [comment]
嗯嗯。哦了。回复的好快。

**Comment by sakmon** [comment]
鸟哥，搞个PHP5支持的版本啊。。

**Comment by laruence** [comment]
@sakmon 我没有时间做PHP5的支持, 如果谁有兴趣可以自己做. 

PHP7的yaconf已经发布在pecl.php.net/yaconf中, windows的dll也在上面可以下载
