### ISSUE TITLE
请问配置引用应该怎么做？

### ISSUE THREAD

**Issue by lovelock** [laruence/yaconf#11]
比如我有一个域名的配置，
env.ini

```
domain=xxxx.weibo.com
```

这时如果我想在同一个配置文件或别的配置文件中（不是在PHP代码中）引用这个domain值，要怎么做呢？因为我会有很多不经常变的配置比如，播放地址、管理后台地址什么的。虽然也可以一遍一遍的写，但在一台多人使用的开发机上配置不同域名的开发环境就比较麻烦了。

希望鸟哥能给指条路

**Comment by laruence** [comment]
没明白你的意思,  大家就用yaconf::get("env.domain")不就行了?

**Comment by lovelock** [comment]
多谢鸟哥回复。

这么说吧，比如在env.ini中，我还有这样的配置

player_domain=xxxx.weibo.com/player
admin_domain=xxxx.weibo.com/admin

那我如果想自己加一个vhost，域名定为yyyy.weibo.com，这些类似xxxx.weibo.com的字段就都需要改。我希望能实现在上面定义一下
domain=xxxx.weibo.com

player_domain={{domain}}/player
admin_domain={{domain}}/admin

这种，这样就只需要改我的主域名了。

当然如果自己写一个部署脚本，把这些批量替换掉也行，但我觉得如果能从配置的写法这个层面上解决可能会更好一点。

**Comment by laruence** [comment]
这个还真没啥好办法, 一个可以行得通的办法是ini中可以使用环境变量.

**Comment by lovelock** [comment]
那有没有可能在yaconf里面实现这个特殊功能呢？比如定义一个不常用的符号，作为引用的标识。

不过这样会增加复杂度。。。

谢谢鸟哥

**Comment by lovelock** [comment]
我以为您说的是在php-fpm.conf里面配置上环境变量，就认为是放在`$_SERVER`里面吧，然后在app.ini中写比如

``` conf
# fpm
env[DOMAIN_NAME] = 'www.ggg.com'
```

``` ini
;ini
domain=DOMAIN_NAME
```

这样是无法取到环境变量的。我看我们的项目中有这样的代码，但实际上还是有个中间的工具类拿到ini中的key再根据值从`$_SERVER`变量里面取的。我是觉得这样的方式还不太完美。。。可能是我想多了。。。
