### ISSUE TITLE
请问有必要使用 yaconf 替代 yaf 中的默认 config 机制吗？

### ISSUE THREAD

**Issue by liuzhao74** [laruence/yaconf#12]
鸟哥好，

首先，在使用 yaf 时， 当 `yaf.cache_config = 1`，采用的 config 机制是否与 yaconfig 是相同的？

如果使用默认的 `yaf.cache_config = 0`，当我需要使用 yaconfig 做配置管理时，应该怎样执行 Yaf_Application 的初始化？

``` php
$application = new Yaf_Application( APPLICATION_PATH . "/conf/application.ini");

//尝试过做如下修改
$application = new Yaf_Application( Yaconf::get("application") );  

//yaconf 获取的 application.ini 与 yaf 下 /conf/application.ini 一致，
//但是抛异常了 “Expected an array of application configure”。
```

看了下 yaf 的文档，

> config
> 关联数组的配置, 或者一个指向ini格式的配置文件的路径的字符串, 或者是一个Yaf_Config_Abstract实例

有点困扰。

是否只能默认采用加载 "/conf/application.ini" 的方式（application.ini 为空文件），然后在 Bootstrap 里定义 _initConfig(), 然后将配置文件通过 yaconf 加载并注册到 yaf 中？

``` php
public function _initConfig() {
    //Yaf_Registry::set('config', Yaf_Application::app()->getConfig());
    Yaf_Registry::set('config', Yaconf::get("application"));
}

//貌似这样依然会抛出异常 “Initialization of application config failed”
```

**Comment by mrcelite** [comment]
亲试，没有问题。请检查php.ini中yaconf的directory目录是否一致

**Comment by WuJiY** [comment]
成功了吗？
