### ISSUE TITLE
关于搭建报错问个问题

### ISSUE THREAD

**Issue by zhyke** [laruence/yaconf#13]
你好,我搭建两次yaconf-1.0.1的,一次是编译安装,一次是pecl 安装,根据您的样例,但是报错了
Fatal error: Uncaught Error: Class 'Yaconf' not found in Command line code:1
我php是7.0.4的,我试着在php.ini里加了extension=yaconf.so 也不行

**Comment by laruence** [comment]
一般都是因为扩展没有正常加载导致的
