### ISSUE TITLE
 配置yaconf.directory 后segmentation fault

### ISSUE THREAD

**Issue by xinhaiz** [laruence/yaconf#14]
➜  tail -f -n 10 etc/php.ini
[redis]
extension="redis.so"

[ast]
extension=ast.so

[Yaconf]
extension=yaconf.so
yaconf.directory="/home/www/yaconf"
yaconf.check_delay=1

➜  php -v
[1]    13598 segmentation fault  php -v

// -------
环境
Mac Pro  - EI Captian 10.11.5
PHP 7.0.5 (cli) (built: Apr 11 2016 02:07:04) ( NTS DEBUG )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

Linux 环境是正常的
CentOS 7.0 
PHP 7.0.6 (cli) (built: May 17 2016 17:11:07) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

//// -----
Mac 开发机 多开了个 DEBUG

**Comment by laruence** [comment]
segfault的backtrace是啥

**Comment by xinhaiz** [comment]
非常特殊的配置：

0x0000000100762571 in zend_hash_str_find_bucket (ht=0x1017bd030, str=0x103002011 "allow", len=5, h=9223372247561362468) at Zend/zend_hash.c:517
517     idx = HT_HASH_EX(arData, nIndex);

ini : 

domain = "xx.com"
domain.allow[] = 'xx.com'
domain.deny[] = ''

前面Linux 下测试没这个配置，所以是通过的，

这个配置在Yaf 是解析通过的

**Comment by laruence** [comment]
整个backtrace都贴出来, 我看看哪里调用的

**Comment by laruence** [comment]
整个backtrace都贴出来, 我看看哪里调用的

**Comment by laruence** [comment]
整个backtrace都贴出来, 我看看哪里调用的

**Comment by xinhaiz** [comment]
#0  0x0000000100762571 in zend_hash_str_find_bucket (ht=0x1030043c0, str=0x102403037 "allow", len=5, h=9223372247561362468) at Zend/zend_hash.c:517
#1  0x00000001007624f4 in zend_hash_str_find (ht=0x1030043c0, str=0x102403037 "allow", len=5) at Zend/zend_hash.c:1995
#2  0x00000001016bfe38 in zend_symtable_str_find () from /usr/local/php/lib/php/extensions/debug-non-zts-20151012/yaconf.so
#3  0x00000001016c1359 in php_yaconf_simple_parser_cb () from /usr/local/php/lib/php/extensions/debug-non-zts-20151012/yaconf.so
#4  0x00000001016c0716 in php_yaconf_ini_parser_cb () from /usr/local/php/lib/php/extensions/debug-non-zts-20151012/yaconf.so
#5  0x00000001006fa9a2 in ini_parse () at Zend/zend_ini_parser.c:1590
#6  0x00000001006fa295 in zend_parse_ini_file (fh=0x7fff5fbfecd8, unbuffered_errors=0 '\000', scanner_mode=0, ini_parser_cb=0x1016c02c0 <php_yaconf_ini_parser_cb>, 
    arg=0x7fff5fbfedf8) at Zend/zend_ini_parser.c:291
#7  0x00000001016bf02e in zm_startup_yaconf () from /usr/local/php/lib/php/extensions/debug-non-zts-20151012/yaconf.so
#8  0x000000010074f4ad in zend_startup_module_ex (module=0x1020066a0) at Zend/zend_API.c:1849
#9  0x000000010074fdb0 in zend_startup_module_zval (zv=0x10180c020) at Zend/zend_API.c:1864
#10 0x000000010076124d in zend_hash_apply (ht=0x100e86028, apply_func=0x10074fd90 <zend_startup_module_zval>) at Zend/zend_hash.c:1534
#11 0x000000010074fbd7 in zend_startup_modules () at Zend/zend_API.c:1975
#12 0x000000010069d3d3 in php_module_startup (sf=0x100e64ca0, additional_modules=0x0, num_additional_modules=0) at main/main.c:2217
#13 0x000000010083839b in php_cli_startup (sapi_module=0x100e64ca0) at sapi/cli/php_cli.c:423
#14 0x00000001008364d5 in main (argc=1, argv=0x7fff5fbffb60) at sapi/cli/php_cli.c:1324

配置上修改:
这个配置本身有问题，非常特殊，我修改配置就OK了

**Comment by laruence** [comment]
你要不把这个配置发给我? laruence at gmail dot com

**Comment by xinhaiz** [comment]
好的。麻烦您了。

**Comment by laruence** [comment]
已经修复了, 周末发布个新版, 谢谢报告 :)
