### ISSUE TITLE
修改配置重新加载建议

### ISSUE THREAD

**Issue by Neverleave** [laruence/yaconf#15]
看了yaconf，如果中间修改了配置，系统会自动检测重新加载，其实配置大部分时间都不会去动，一直有个检测在跑其实也有一定的资源消耗，虽然很小。建议弄成触发式的重新加载，之后有一些yaconf管理后台的话也可以手动重新加载。小小建议😄

**Comment by laruence** [comment]
你可以设置60s检测一次, 这个开销就很小了, 几乎可以忽略不计了
