### ISSUE TITLE
ini文件删除之后，配置项仍长期常驻内存（已设定check_delay为300）

### ISSUE THREAD

**Issue by yyxx9988** [laruence/yaconf#16]
这个一个BUG

**Comment by farwish** [comment]
php-7.0.9   yaconf-1.0.2  试了没有这个问题，check_delay 设置和不设置都没有出现这种情况（注：delay默认是300）

**Comment by laruence** [comment]
只能被覆盖, 实现限制的妥协.

**Comment by yyxx9988** [comment]
那就是说，要想删除配置内存，只能先重置ini配置内容为空，然后再删除ini文件，鸟哥？ @laruence

**Comment by laruence** [comment]
你可以放一个空个配置文件上去(或者重启, 推荐更新配置以后重启)

**Comment by yyxx9988** [comment]
OK
