### ISSUE TITLE
希望支持以对象形式访问

### ISSUE THREAD

**Issue by flyhope** [laruence/yaconf#18]
我们项目想从Yaf的Yaf_Config_Ini转向yaconf配置文件，期间遇到一个问题，如果yaconf获取的一个节点包含子节点，返回的是一个数组，只能用$config['xxx']访问。

而Yaf_Config_ini返回的是一个Yaf_Config_ini对象，可以用$config['xxx']访问，也可以用$config->xxx访问。

希望返回值是一个类似于Yaf_Config_ini的对象，可以用数组访问，也可用对象访问，这样改动不是很大

**Comment by laruence** [comment]
如果是返回对象, 就不能做到零拷贝了,  所以鼓励大家使用数组方式.
