### ISSUE TITLE
不重启php-fpm，能reload数据么

### ISSUE THREAD

**Issue by munggruel** [laruence/yaconf#22]
目前有些游戏的模版表数据存在yac里面，yaconf是不是性能更好，不重启 php-fpm能reload数据么
类似 opcache那种 opcache_reset() 功能

**Comment by munggruel** [comment]
类似 opcache那种 opcache_reset() 功能

**Comment by dilllay** [comment]
Features 里面清晰写明了 Configurations reload automatically after changed
请认真阅读

**Comment by munggruel** [comment]
实际上有一些模版数据在开发过程中会更新，动态加载就是不能立即生效，类似代码的热加载一样，开发调试过程是有意义的

**Comment by dilllay** [comment]
这么说吧，我在实际的开发过程中，我要求我的团队开发人员修改了yaconf的配置后，都重启一下php-fpm，一方面来说保证准确加载，另一方面来说，项目配置的修改并不频繁，多一步这样的操作是可以接受的。另外，yaconf这个项目的目的是在生产环境的运用，每一次生产环境的git checkout都会触碰mtime，所以生产环境的准确性应该已经保障了呢。如果因为这个特性对你造成烦恼的话，那么你可以选择crontab，如果你嫌弃crontab 频率太低的话，npm有一个好像叫Gruntfile的东西，它可以检测指定文件夹被修改后而执行某些操作

**Comment by laruence** [comment]
如果不是ZTS的, yaconf会检测变动后加载, 但是检测的是yaf.directory的mtime
