### ISSUE TITLE
不会出现与文件不完全一致的时候吗？

### ISSUE THREAD

**Issue by jdl13** [laruence/yaconf#3]
| a.ini（前） | a.ini（修改中） | a.ini（后） |
| --- | --- | --- |
| a=1 | a=2 | a=2 |
| b=1 | b=1 | b=2 |

在yaconf检测到需要修改的时候直接修改了mtime，内容只修改了a没修改b，但是有别的请求读取的时候mtime已经更新，不会去读文件，读取出来的a和b不会是跟文件不一致的吗？复制一个新的临时变量，更新为文件的内容，再替换指针保证变量的内容跟文件的保持一致，会不会好一点？

**Comment by laruence** [comment]
我们建议, 更新文件用mv, 不要copy. 这个应该是部署上线的一个共识了吧. 所以没有必要弄的实现复杂, 遵循这个约定俗成的规矩即可.
