### ISSUE TITLE
Found a cause of php-fpm process crash situation

### ISSUE THREAD

**Issue by tianmingxing** [laruence/yaconf#32]
I follow the steps below and found that the php-fpm process can not parse the php file normally, but the process is not broken, but it can not handle the request. Through the browser request to get a 502 error.

1. Install the latest version of yaconf
2. Go to the php.ini file to set the path
3. But the path does not exist
4. Create this path manually
5. There was a strange question that php-fpm could not work properly.

Whether it is due to the problem of the module itself.

**Comment by laruence** [comment]
this should be fixed.
