### ISSUE TITLE
是否可以增加对子级目录的支持

### ISSUE THREAD

**Issue by period331** [laruence/yaconf#37]
yaconf.directory=/path/to

子集目录：/path/to/a/app.conf
```
name=123
```

var_dump(Yaconf::get("/a/app.name"));
```
string(3) "123"
```

**Comment by azhai** [comment]
参考项目  [yaconf_zx](https://github.com/xinzou/yaconf_zx)

**Comment by ghost** [comment]
有必要支持子目录吗？
/ 用 - 替代 完美解决
最最重要的是，不用多扫描一次子目录

**Comment by ghost** [comment]
如果真的要支持子目录或分散到不同的目录，不是还有 ln 吗，有了ln 你爱多少层多少层，爱放哪放哪

**Comment by JinPengCN** [comment]
同问，多项目部署在同一台机器上很常见的场景，需要多个子目录来区分一下

**Comment by letwang** [comment]
https://github.com/laruence/yac/issues/122#issuecomment-1129456461

**Comment by laruence** [comment]
已经增加支持， https://github.com/laruence/yaconf/commit/b65bd0de09540caa28e0dcdda8dbe66b83b1e96a
