### ISSUE TITLE
总觉得ini配置文件，表达能力还是弱了点

### ISSUE THREAD

**Issue by wuxue107** [laruence/yaconf#39]
要做个屏蔽词检测的部件，会将几千个屏蔽词生成类似这样的接口
`
[
    'f' => [
         'u'  => [
                  'a' => '$end',
                  'c' => [
                          'k'  => '$end'
                  ]
          ]
    ]
]
`
想用Yaconf做配置，但是生成的结构不太容易导出，还有一个中文特殊字符等问题，如果能支持json或者php做配置文件就更好了

**Comment by laruence** [comment]
你可以写一个脚本.....生成ini啊... :)

**Comment by laruence** [comment]
不过,  对于你说的这种情况, 词表类的, 他应该不是"配置", 量很大, 更新也会频繁, 不如用memcache之类的
