### ISSUE TITLE
求解答

### ISSUE THREAD

**Issue by chrysanthemum** [laruence/yaconf#41]
在 PHP_MINIT_FUNCTION 里面更新配置到 ini_containers 变量，只读取配置文件一次。
在 PHP_RINIT_FUNCTION 里面，如果检测到配置文件发生变化了，则每个进程创建后，都需要从这里读取配置文件一次来更新每个进程的 ini_containers 变量。

这样理解对吗? 谢谢啦~

**Comment by laruence** [comment]
对.. 所以推荐还是更新以后重启... 这样内存占用是最小的
