### ISSUE TITLE
fpm 下 mtime 无法更新

### ISSUE THREAD

**Issue by infatu8** [laruence/yaconf#43]
fpm下
==========
![image](https://user-images.githubusercontent.com/7835780/47254140-53bbdd00-d490-11e8-8588-bd3cfcf1dacb.png)

cli 下
==========

$ php -v
PHP 7.2.10 (cli) (built: Oct 11 2018 22:20:07) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10, Copyright (c) 1999-2018, by Zend Technologies

----------

$ php -i | grep -A10 yaconf
yaconf
yaconf support => enabled
version => 1.0.7
yaconf config last check time => Sat Oct 20 17:57:19 2018
parsed filename => mtime
test.ini => Sat Oct 20 17:45:03 2018
Directive => Local Value => Master Value
yaconf.check_delay => 5 => 5
yaconf.directory => /webroot/.Yaconf => /webroot/.Yaconf

----------

$ stat test.ini 
  File: test.ini
  Size: 10        	Blocks: 8          IO Block: 4096   regular file
Device: 811h/2065d	Inode: 932512      Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/    bobo)   Gid: ( 1000/    bobo)
Access: 2018-10-20 17:33:05.924045838 +0800
Modify: 2018-10-20 17:45:03.085220849 +0800
Change: 2018-10-20 17:45:03.085220849 +0800
 Birth: -

**Comment by yulonghu** [comment]
CLI 与 PHP-FPM 是两种不同的模式。
