### ISSUE TITLE
yaconf在php7.3下安装失败

### ISSUE THREAD

**Issue by Justin0530** [laruence/yaconf#46]
/home/webb.m/source/yaconf-yaconf-1.0.6/yaconf.c: In function ‘php_yaconf_hash_init’:
/home/webb.m/source/yaconf-yaconf-1.0.6/yaconf.c:92:15: error: lvalue required as left operand of assignment
  GC_FLAGS(ht) |= IS_ARRAY_IMMUTABLE;
               ^
/home/webb.m/source/yaconf-yaconf-1.0.6/yaconf.c:93:18: error: lvalue required as left operand of assignment
  GC_REFCOUNT(ht) = 2;
                  ^
/home/webb.m/source/yaconf-yaconf-1.0.6/yaconf.c:98:23: error: ‘IS_TYPE_COPYABLE’ undeclared (first use in this function)
  Z_TYPE_FLAGS_P(zv) = IS_TYPE_COPYABLE;
                       ^
/home/webb.m/source/yaconf-yaconf-1.0.6/yaconf.c:98:23: note: each undeclared identifier is reported only once for each function it appears in
/home/webb.m/source/yaconf-yaconf-1.0.6/yaconf.c: In function ‘php_yaconf_str_persistent’:
/home/webb.m/source/yaconf-yaconf-1.0.6/yaconf.c:144:16: error: lvalue required as left operand of assignment
  GC_FLAGS(key) |= IS_STR_INTERNED | IS_STR_PERMANENT;
                ^
/home/webb.m/source/yaconf-yaconf-1.0.6/yaconf.c: In function ‘php_yaconf_zval_persistent’:
/home/webb.m/source/yaconf-yaconf-1.0.6/yaconf.c:166:8: error: ‘IS_CONSTANT’ undeclared (first use in this function)
   case IS_CONSTANT:
        ^
make: *** [yaconf.lo] Error 1

我用的php7.3 系统是centos centos-release-7-5.1804.el7.centos.x86_64
我使用了pecl 和源码安装都出现了同样的问题。

**Comment by laruence** [comment]
试用最新版本的Yaconf, pecl上下载

**Comment by 1sting** [comment]
> 试用最新版本的Yaconf, pecl上下载

php7.4编译也失败了， pecl上也是1.0.7的版本，也不通过。

**Comment by laruence** [comment]
目前应该是可以了，1.0.8版本
