### ISSUE TITLE
php-7.3.1编辑错误

### ISSUE THREAD

**Issue by infatu8** [laruence/yaconf#49]
/usr/local/src/php-7.3.1/ext/yaconf/yaconf.c: In function ‘php_yaconf_hash_init’:
/usr/local/src/php-7.3.1/ext/yaconf/yaconf.c:90:15: error: lvalue required as left operand of assignment
  GC_FLAGS(ht) |= IS_ARRAY_IMMUTABLE;
               ^~
/usr/local/src/php-7.3.1/ext/yaconf/yaconf.c:91:15: error: lvalue required as left operand of assignment
  GC_FLAGS(ht) |= HASH_FLAG_STATIC_KEYS;
               ^~
/usr/local/src/php-7.3.1/ext/yaconf/yaconf.c:95:19: error: ‘HASH_FLAG_APPLY_PROTECTION’ undeclared (first use in this function); did you mean ‘_SC_MEMORY_PROTECTION’?
  GC_FLAGS(ht) &= ~HASH_FLAG_APPLY_PROTECTION;
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
                   _SC_MEMORY_PROTECTION
/usr/local/src/php-7.3.1/ext/yaconf/yaconf.c:95:19: note: each undeclared identifier is reported only once for each function it appears in
/usr/local/src/php-7.3.1/ext/yaconf/yaconf.c:98:18: error: lvalue required as left operand of assignment
  GC_REFCOUNT(ht) = 2;
                  ^
/usr/local/src/php-7.3.1/ext/yaconf/yaconf.c:103:23: error: ‘IS_TYPE_COPYABLE’ undeclared (first use in this function); did you mean ‘Z_OPT_COPYABLE’?
  Z_TYPE_FLAGS_P(zv) = IS_TYPE_COPYABLE;
                       ^~~~~~~~~~~~~~~~
                       Z_OPT_COPYABLE
/usr/local/src/php-7.3.1/ext/yaconf/yaconf.c: In function ‘php_yaconf_str_persistent’:
/usr/local/src/php-7.3.1/ext/yaconf/yaconf.c:149:16: error: lvalue required as left operand of assignment
  GC_FLAGS(key) |= IS_STR_INTERNED | IS_STR_PERMANENT;
                ^~
/usr/local/src/php-7.3.1/ext/yaconf/yaconf.c: In function ‘php_yaconf_zval_persistent’:
/usr/local/src/php-7.3.1/ext/yaconf/yaconf.c:171:8: error: ‘IS_CONSTANT’ undeclared (first use in this function); did you mean ‘RT_CONSTANT’?
   case IS_CONSTANT:
        ^~~~~~~~~~~
        RT_CONSTANT
Makefile:194: recipe for target 'yaconf.lo' failed
make: *** [yaconf.lo] Error 1

**Comment by OMGZui** [comment]
php-7.3.1同样遇到该问题

**Comment by phoenixg** [comment]
please support php 7.3.x

**Comment by yulonghu** [comment]
这个问题，可以关啦，已经修复啦。
