### ISSUE TITLE
php 7.3.4 make error

### ISSUE THREAD

**Issue by tangchao1992** [laruence/yaconf#50]
鸟哥,今天编译时发生下面这个错误
`/home/tangchao/Downloads/yaconf-yaconf-1.0.7/yaconf.c:` In function ‘php_yaconf_hash_init’:
`/home/tangchao/Downloads/yaconf-yaconf-1.0.7/yaconf.c:90:15: error: lvalue required as left operand of assignment
`  GC_FLAGS(ht) |= IS_ARRAY_IMMUTABLE;
`              ^~
`/home/tangchao/Downloads/yaconf-yaconf-1.0.7/yaconf.c:91:15: error: lvalue required as left operand of assignment
`  GC_FLAGS(ht) |= HASH_FLAG_STATIC_KEYS;
               ^~
`/home/tangchao/Downloads/yaconf-yaconf-1.0.7/yaconf.c:95:19: error: `‘HASH_FLAG_APPLY_PROTECTION’ undeclared (first use in this function); did you mean `‘_SC_MEMORY_PROTECTION’?
`  GC_FLAGS(ht) &= ~HASH_FLAG_APPLY_PROTECTION;
`                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
`                   _SC_MEMORY_PROTECTION
`/home/tangchao/Downloads/yaconf-yaconf-1.0.7/yaconf.c:95:19: note: each undeclared identifier is reported only once for each function it appears in
`/home/tangchao/Downloads/yaconf-yaconf-1.0.7/yaconf.c:98:18: error: lvalue required as left operand of assignment
`  GC_REFCOUNT(ht) = 2;
                  ^
`/home/tangchao/Downloads/yaconf-yaconf-1.0.7/yaconf.c:103:23: error: ‘IS_TYPE_COPYABLE’ `undeclared (first use in this function); did you mean ‘Z_OPT_COPYABLE’?
`  Z_TYPE_FLAGS_P(zv) = IS_TYPE_COPYABLE;
`                       ^~~~~~~~~~~~~~~~
`                       Z_OPT_COPYABLE
`/home/tangchao/Downloads/yaconf-yaconf-1.0.7/yaconf.c: In function ‘php_yaconf_str_persistent’:
`/home/tangchao/Downloads/yaconf-yaconf-1.0.7/yaconf.c:149:16: error: lvalue required as left operand of assignment
`  GC_FLAGS(key) |= IS_STR_INTERNED | IS_STR_PERMANENT;
`                ^~
`/home/tangchao/Downloads/yaconf-yaconf-1.0.7/yaconf.c: In function ‘php_yaconf_zval_persistent’:
`/home/tangchao/Downloads/yaconf-yaconf-1.0.7/yaconf.c:171:8: error: ‘IS_CONSTANT’ undeclared `(first use in this function); did you mean ‘RT_CONSTANT’?
`   case IS_CONSTANT:
`        ^~~~~~~~~~~
`        RT_CONSTANT
`make: *** [Makefile:194：yaconf.lo] 错误 1

**Comment by infatu8** [comment]
遇到同样问题
----------
/usr/local/src/yaconf-1.0.7/yaconf.c: In function ‘php_yaconf_hash_init’:
/usr/local/src/yaconf-1.0.7/yaconf.c:90:15: error: lvalue required as left operand of assignment
  GC_FLAGS(ht) |= IS_ARRAY_IMMUTABLE;
               ^~
/usr/local/src/yaconf-1.0.7/yaconf.c:91:15: error: lvalue required as left operand of assignment
  GC_FLAGS(ht) |= HASH_FLAG_STATIC_KEYS;
               ^~
/usr/local/src/yaconf-1.0.7/yaconf.c:95:19: error: ‘HASH_FLAG_APPLY_PROTECTION’ undeclared (first use in this function); did you mean ‘_SC_MEMORY_PROTECTION’?
  GC_FLAGS(ht) &= ~HASH_FLAG_APPLY_PROTECTION;
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
                   _SC_MEMORY_PROTECTION
/usr/local/src/yaconf-1.0.7/yaconf.c:95:19: note: each undeclared identifier is reported only once for each function it appears in
/usr/local/src/yaconf-1.0.7/yaconf.c:98:18: error: lvalue required as left operand of assignment
  GC_REFCOUNT(ht) = 2;
                  ^
/usr/local/src/yaconf-1.0.7/yaconf.c:103:23: error: ‘IS_TYPE_COPYABLE’ undeclared (first use in this function); did you mean ‘Z_OPT_COPYABLE’?
  Z_TYPE_FLAGS_P(zv) = IS_TYPE_COPYABLE;
                       ^~~~~~~~~~~~~~~~
                       Z_OPT_COPYABLE
/usr/local/src/yaconf-1.0.7/yaconf.c: In function ‘php_yaconf_str_persistent’:
/usr/local/src/yaconf-1.0.7/yaconf.c:149:16: error: lvalue required as left operand of assignment
  GC_FLAGS(key) |= IS_STR_INTERNED | IS_STR_PERMANENT;
                ^~
/usr/local/src/yaconf-1.0.7/yaconf.c: In function ‘php_yaconf_zval_persistent’:
/usr/local/src/yaconf-1.0.7/yaconf.c:171:8: error: ‘IS_CONSTANT’ undeclared (first use in this function); did you mean ‘RT_CONSTANT’?
   case IS_CONSTANT:
        ^~~~~~~~~~~
        RT_CONSTANT
Makefile:194: recipe for target 'yaconf.lo' failed
make: *** [yaconf.lo] Error 1

----------
php -v
PHP 7.3.4 (cli) (built: Apr 11 2019 22:37:09) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.4, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.4, Copyright (c) 1999-2018, by Zend Technologies

**Comment by infatu8** [comment]
下载master编译通过

**Comment by sijianglong** [comment]
下载主编译通过，可以详细说下吗？主编译在哪下载的啊
