### ISSUE TITLE
开发环境下支持

### ISSUE THREAD

**Issue by wuxue107** [laruence/yaconf#53]
我有多个开发环境dev1 、dev2 ...
我现在的做法，入口文件加了个常量APP_ENV = 'dev1';自己加了个Appconf::get 在方法里调用
Yaconf::get(APP_ENV . '_' . $key);
然后配置文件名都是这样 dev1_common.ini 、dev2_common.ini ..

但在各开发环境中，大部分参数都是一样的，只有配置里service_getway里面对应的服务参数不一样，每次修改，都要修改每个文件。
能否加入跨文件的Section继承
或者从文件名上的"."号已可以参与到数据的覆盖上如： dev1_common.service_getway.ini就可以给dev1_common.ini的配置文件补充service_getway部分的数据
或单文件内[dev1.service_getway: base.service_getway] 多层级的继承

**Comment by laruence** [comment]
跨文件的节继承会比较麻烦，需要保证文件的parse顺序，不是很优雅。
我建议你可以把Service_getway定义为环境变量？ 然后在 ini中引用？
