### ISSUE TITLE
windows下php7.2的1.06和1.07版本都不支持盘符

### ISSUE THREAD

**Issue by renxiaotu** [laruence/yaconf#54]
windows下php7.2的1.06和1.07版本
yaconf.directory配置盘符时php无法启动且没有php的错误日志
换成类似Linux的/开头后可正常启动php，但无法读取配置（windows下是盘符开头）
希望鸟哥更新一下

**Comment by renxiaotu** [comment]
更正一下，看了鸟哥博客下的评论，自己也测试了一下，不是不支持盘符，是如果为directory设置一个不存在的目录，PHP可以启动，如果一个存在的目录，不管是空目录还是有INI文件，PHP都启动不起来

**Comment by laruence** [comment]
我没有windows环境，不太好弄，谁可以的话，帮忙弄个PR吧。thanks

**Comment by renxiaotu** [comment]
感谢鸟哥回复，今天看到在2019-12-23更新了1.0.8版本，就抱着试一试的态度，竟然这个问题被修复了，现在用1.0.8版本已经不存在该错误，可惜我看不懂源代码不知道是什么原理，感谢大佬的更新
