### ISSUE TITLE
Configurations not reload automatically after changed

### ISSUE THREAD

**Issue by JorsonChen** [laruence/yaconf#56]
Configurations reload automatically after config files changed ?
Why I didn't achieve it？

**Comment by JorsonChen** [comment]
my phpinfo show as follows

- version:1.0.9-dev

- yaconf config last check time:Mon Feb 17 02:52:23 2020

- yaconf.check_delay:300

what check delay mean?
please help，thanks

**Comment by laruence** [comment]
yaconf checks the mtime of the yaf.directioy , so you should check whether it was changed after you edited the config files

**Comment by JorsonChen** [comment]
> yaconf checks the mtime of the yaf.directioy , so you should check whether it was changed after you edited the config files

I'm sure I've edited the profile and saved it,maybe I know what happened,thank you.
