### ISSUE TITLE
Yaconf 加入 数据库连接池功能

### ISSUE THREAD

**Issue by chrysanthemum** [laruence/yaconf#64]
@laruence 鸟哥，您好！

一个不成熟的想法：数据库每次连接的成本有点高，如果把数据库连接池的功能加入Yaconf，填补了fpm的一大短板，我想收益蛮大的。

不知是否可以考虑？
感谢！

**Comment by mowangjuanzi** [comment]
https://www.php.net/manual/zh/features.persistent-connections.php 这里就有哇
