### ISSUE TITLE
PHP8.1安装Yaconf1.1.1导致数据解析错误

### ISSUE THREAD

**Issue by letwang** [laruence/yaconf#67]
![image](https://user-images.githubusercontent.com/3644168/147544095-f7e589bd-5ad0-4daf-b39f-7547b4f8d597.png)
```
var_dump(
    Yaconf::get('dicRegexp'),
    Yaconf::get('adminProduct'),
    Yaconf::get('storeTable')
);
```

如题，我的项目配置文件：https://github.com/letwang/HookPHP/tree/master/conf

现在每个ini文件无法根据key正确查找到内容，无论我更换什么key，输出的结果都是一样的。

**Comment by letwang** [comment]
![image](https://user-images.githubusercontent.com/3644168/151651151-b1b0960d-5165-4ab0-a532-25b07a011d99.png)
经过测试，无论Yaconf读取哪个文件名称，值永远都是第1个文件中的值，这的确是个BUG，期待大佬早日修复 祝我HookPHP腾飞~
新年快乐~

**Comment by letwang** [comment]
![image](https://user-images.githubusercontent.com/3644168/157360970-0994c204-cce7-469a-8930-1fb0831ebbc5.png)
https://www.php.net/manual/zh/yaconf.configuration.php#ini.yaconf.directory

可能是这点 加载所有INI文件时 出错了，大佬 抽空修复吧 毕竟PHP是世界最好的语言~

**Comment by aguoge-01** [comment]
是的，我刚才也碰上了一样的问题，只解析到第一个文件，但 has 就解析到文件了

**Comment by letwang** [comment]
https://github.com/laruence/yac/issues/122#issuecomment-1129456461

**Comment by laruence** [comment]
fixed, thanks for reporting.
