### ISSUE TITLE
一个长期运行的脚本 读取配置 并不会自动变化

### ISSUE THREAD

**Issue by holla-renzhenguo** [laruence/yaconf#71]
我运行了一个由supervisor守护的脚本，用来处理队列数据

当我更新了ini文件配置后 ，使用fastcgi访问的程序已经变更，但是 该脚本在不重启的情况下 获取到的配置值没有变更

**Comment by lieshanhe** [comment]
检查一下yaconf.check_delay。
https://github.com/laruence/yaconf#runtime-configuration
这里有说明的。

**Comment by holla-renzhenguo** [comment]
> 

设置了的， 使用接口访问或者重新启动的脚本获取到是变化后的值了。 而一直在运行的脚本 每次去获取 都是原来的值

**Comment by holla-renzhenguo** [comment]
> 检查一下yaconf.check_delay。 https://github.com/laruence/yaconf#runtime-configuration 这里有说明的。

设置了的， 使用接口访问或者重新启动的脚本获取到是变化后的值了。 而一直在运行的脚本 每次去获取 都是原来的值

**Comment by holla-renzhenguo** [comment]
@laruence 大佬 有什么解决的办法吗

**Comment by easydowork** [comment]
> @laruence 大佬 有什么解决的办法吗
文档说了 我也是才发现 更新ini文件后,还要修改一下配置目录(yaconf.directory)的访问时间,eg:
```php
touch('/tmp/php_yaconf');
```

**Comment by holla-renzhenguo** [comment]
> > @laruence 大佬 有什么解决的办法吗
> > 文档说了 我也是才发现 更新ini文件后,还要修改一下配置目录(yaconf.directory)的访问时间,eg:
> 
> ```
> touch('/tmp/php_yaconf');
> ```

可能是我问题没有表述清楚

我修改配置后 访问api接口 和 新运行的脚本，都可以正常获取到变更后的配置。
而正在运行的脚本 获取到的还是修改前的值。
 
也就是说 脚本在运行初始化的时候加载了配置 在之后的运行过程中 不会再更新配置了
我有些消费队列数据的脚本，启动后就一直在运行了，我希望他们读取到的配置也能实时变更 而不需要重启脚本。

**Comment by drttcrh** [comment]
@holla-renzhenguo 问一下最后是怎么解决的
